services:
  - type: web
    name: swagyoshop
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: db4free.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: swagyoshop
      - key: DB_USERNAME
        value: swagyo
      - key: DB_PASSWORD
        value: swagyo123
