services:
  - type: web
    name: swagyo-shop
    env: docker
    plan: free
    repo: https://github.com/swagyoofficiall/SwagyoShop
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.yhobhontexaanutlubou.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: yhobhontexaanutlubou
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: 9535118217@$&~K
      - key: APP_KEY
        generateValue: true
